name: 🐛 Bug Report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected X to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, Y happened...
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., macOS 12.0
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 16.13.0
    validations:
      required: true

  - type: input
    id: npm
    attributes:
      label: npm Version
      description: What version of npm are you using?
      placeholder: e.g., 8.1.0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: mementor-ts Version
      description: What version of mementor-ts are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other relevant information...
