blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/your-username/mementor-ts/wiki
    about: Check our documentation before creating an issue
  - name: 💬 Discussions
    url: https://github.com/your-username/mementor-ts/discussions
    about: Ask questions and discuss with other community members
